{% set version = "0.1.0" %}

package:
  name: pypack
  version: {{ version }}

source:
  git_url: https://github.com/CANIS-NAU/PyPACK
  git_rev: master

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  skip: True  # [not py3k]

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - libpypack

about:
  home: https://github.com/CANIS-NAU/PyPACK
  license: Unlicense
